-- Disable verbose logging messages (PostgreSQL specific)
SET client_min_messages = WARNING;

-- ==========================================
-- CREATE TABLES IF NOT EXISTS
-- ==========================================

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(150) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quiz_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    max_attempts INTEGER NOT NULL,
    max_duration NUMERIC(21,0) NOT NULL,
    passing_score VARCHAR(5) NOT NULL,
    quiz_id BIGINT UNIQUE,
    difficulty VARCHAR(255) CHECK (difficulty IN ('BEGINNER','INTERMEDIATE','EXPERT')),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(400) NOT NULL,
    status VARCHAR(255) CHECK (status IN ('DRAFT','UN_PUBLISHED','PUBLISHED')),
    category_id BIGINT,
    settings_id BIGINT UNIQUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_text VARCHAR(255),
    explanation VARCHAR(255),
    marks INTEGER,
    difficulty SMALLINT CHECK (difficulty BETWEEN 0 AND 2),
    quiz_id BIGINT,
    created_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    option_text VARCHAR(255),
    is_correct BOOLEAN,
    question_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    quiz_id BIGINT,
    student_id UUID,
    status VARCHAR(255) CHECK (status IN ('IN_PROGRESS','INTERUPTED','SUBMITTED','COMPLETED')),
    correct_answers INTEGER,
    un_answered INTEGER,
    score FLOAT(53),
    percentage FLOAT(53),
    timetaken NUMERIC(21,0),
    attempt_time TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attempt_id BIGINT,
    question_id BIGINT,
    option_id BIGINT,
    is_correct BOOLEAN,
    PRIMARY KEY (id)
);

-- ==========================================
-- ADD CONSTRAINTS
-- ==========================================

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkabia1j6j2c2p4e5nm19abajv') THEN
        ALTER TABLE answers ADD CONSTRAINT FKabia1j6j2c2p4e5nm19abajv FOREIGN KEY (attempt_id) REFERENCES attempts;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk3erw1a3t0r78st8ty27x6v3g1') THEN
        ALTER TABLE answers ADD CONSTRAINT FK3erw1a3t0r78st8ty27x6v3g1 FOREIGN KEY (question_id) REFERENCES questions;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkn0s3utny5xipstu14dx3mdmfw') THEN
        ALTER TABLE answers ADD CONSTRAINT FKn0s3utny5xipstu14dx3mdmfw FOREIGN KEY (option_id) REFERENCES options;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fko6h1pu3ag91imtsowbsrqbf0a') THEN
        ALTER TABLE attempts ADD CONSTRAINT FKo6h1pu3ag91imtsowbsrqbf0a FOREIGN KEY (quiz_id) REFERENCES quizzes;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk5bmv46so2y5igt9o9n9w4fh6y') THEN
        ALTER TABLE options ADD CONSTRAINT FK5bmv46so2y5igt9o9n9w4fh6y FOREIGN KEY (question_id) REFERENCES questions;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkn3gvco4b0kewxc0bywf1igfms') THEN
        ALTER TABLE questions ADD CONSTRAINT FKn3gvco4b0kewxc0bywf1igfms FOREIGN KEY (quiz_id) REFERENCES quizzes;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkdj1x6br7e0sqx7y9n9yy2nc6a') THEN
        ALTER TABLE quiz_settings ADD CONSTRAINT FKdj1x6br7e0sqx7y9n9yy2nc6a FOREIGN KEY (quiz_id) REFERENCES quizzes;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkpo9fnqd9hnnmg8qxiyue40cot') THEN
        ALTER TABLE quizzes ADD CONSTRAINT FKpo9fnqd9hnnmg8qxiyue40cot FOREIGN KEY (category_id) REFERENCES categories;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkb2ylknlgvbnlvek8536jq6cmc') THEN
        ALTER TABLE quizzes ADD CONSTRAINT FKb2ylknlgvbnlvek8536jq6cmc FOREIGN KEY (settings_id) REFERENCES quiz_settings;
    END IF;
END $$;