-- Disable verbose logging messages (PostgreSQL specific)
SET client_min_messages = WARNING;

-- ==========================================
-- CREATE TABLES IF NOT EXISTS (with Foreign Keys)
-- ==========================================

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(150) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quiz_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    max_attempts INTEGER NOT NULL,
    max_duration NUMERIC(21,0) NOT NULL,
    passing_score VARCHAR(5) NOT NULL,
    quiz_id BIGINT UNIQUE,
    difficulty VARCHAR(255) CHECK (difficulty IN ('BEGINNER','INTERMEDIATE','EXPERT')),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(400) NOT NULL,
    status VARCHAR(255) CHECK (status IN ('DRAFT','UN_PUBLISHED','PUBLISHED')),
    category_id BIGINT CONSTRAINT fkpo9fnqd9hnnmg8qxiyue40cot REFERENCES categories(id),
    settings_id BIGINT UNIQUE CONSTRAINT fkb2ylknlgvbnlvek8536jq6cmc REFERENCES quiz_settings(id),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_text VARCHAR(255),
    explanation VARCHAR(255),
    marks INTEGER,
    difficulty SMALLINT CHECK (difficulty BETWEEN 0 AND 2),
    quiz_id BIGINT CONSTRAINT fkn3gvco4b0kewxc0bywf1igfms REFERENCES quizzes(id),
    created_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    option_text VARCHAR(255),
    is_correct BOOLEAN,
    question_id BIGINT CONSTRAINT fk5bmv46so2y5igt9o9n9w4fh6y REFERENCES questions(id),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    quiz_id BIGINT CONSTRAINT fko6h1pu3ag91imtsowbsrqbf0a REFERENCES quizzes(id),
    student_id UUID,
    status VARCHAR(255) CHECK (status IN ('IN_PROGRESS','INTERUPTED','SUBMITTED','COMPLETED')),
    correct_answers INTEGER,
    un_answered INTEGER,
    score FLOAT(53),
    percentage FLOAT(53),
    timetaken NUMERIC(21,0),
    attempt_time TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attempt_id BIGINT CONSTRAINT fkabia1j6j2c2p4e5nm19abajv REFERENCES attempts(id),
    question_id BIGINT CONSTRAINT fk3erw1a3t0r78st8ty27x6v3g1 REFERENCES questions(id),
    option_id BIGINT CONSTRAINT fkn0s3utny5xipstu14dx3mdmfw REFERENCES options(id),
    is_correct BOOLEAN,
    PRIMARY KEY (id)
);


-- ==========================================
-- INDEXES
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_quizzes_category ON quizzes(category_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_created_at ON quizzes(created_at);
CREATE INDEX IF NOT EXISTS idx_quizzes_title_fts ON quizzes USING gin (to_tsvector('english', title));