-- Disable verbose logging messages (PostgreSQL specific)
SET client_min_messages = WARNING;

-- ==========================================
-- CREATE TABLES IF NOT EXISTS (with Foreign Keys)
-- ==========================================
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(150) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS quiz_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id UUID UNIQUE,
    max_attempts INTEGER NOT NULL,
    max_duration NUMERIC(21,0) NOT NULL,
    passing_score VARCHAR(5) NOT NULL,
    difficulty VARCHAR(50) CHECK (difficulty IN ('BEGINNER','INTERMEDIATE','EXPERT')),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS quizzes (
    id UUID PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(400) NOT NULL,
    status VARCHAR(50) CHECK (status IN ('DRAFT','UN_PUBLISHED','PUBLISHED')),
    category_id BIGINT,
    settings_id BIGINT UNIQUE,
    is_deleted BOOLEAN,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_quizzes_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_quizzes_settings FOREIGN KEY (settings_id) REFERENCES quiz_settings(id)
);

-- Idempotent Circular FK for Quiz Settings
ALTER TABLE quiz_settings DROP CONSTRAINT IF EXISTS fk_quiz_settings_quiz;
ALTER TABLE quiz_settings ADD CONSTRAINT fk_quiz_settings_quiz FOREIGN KEY (quiz_id) REFERENCES quizzes(id);

CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id UUID,
    question_text VARCHAR(1000),
    explanation TEXT,
    marks INTEGER,
    difficulty VARCHAR(50) CHECK (difficulty IN ('BEGINNER','INTERMEDIATE','EXPERT')),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_questions_quiz FOREIGN KEY (quiz_id) REFERENCES quizzes(id)
);

CREATE TABLE IF NOT EXISTS options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT,
    option_text TEXT,
    is_correct BOOLEAN,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_options_question FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE TABLE IF NOT EXISTS attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id UUID,
    student_id UUID,
    status VARCHAR(50) CHECK (status IN ('IN_PROGRESS','INTERUPTED','SUBMITTED','AUTO_COMPLETED')),
    score INTEGER,
    correct_answers INTEGER,
    un_answered INTEGER,
    percentage FLOAT(53),
    time_spent NUMERIC(21,0),
    updated_at TIMESTAMP(6) NOT NULL,
    attempt_time TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_attempts_quiz FOREIGN KEY (quiz_id) REFERENCES quizzes(id)
);

CREATE TABLE IF NOT EXISTS answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT,
    question_id BIGINT,
    option_id BIGINT,
    is_correct BOOLEAN,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_answers_attempt FOREIGN KEY (attempt_id) REFERENCES attempts(id),
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT fk_answers_option FOREIGN KEY (option_id) REFERENCES options(id)
);

-- ==========================================
-- INDEXES
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_quizzes_category ON quizzes(category_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_created_at ON quizzes(created_at);
CREATE INDEX IF NOT EXISTS idx_quizzes_title_fts ON quizzes USING gin (to_tsvector('english', title));
CREATE INDEX IF NOT EXISTS idx_categories_title_fts ON categories USING gin (to_tsvector('english', name));