management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: refresh,health

services:
    uri:
        identity: http://qoap-identity-service/identity/api/v1
        quiz: http://qoap-quiz-service/quiz/api/v1
        reports: http://qoap-reports-service/reports/api/v1

eureka:
    props:
        defaultZone: http://localhost:8761/eureka
        hostname: localhost
    client:
        register-with-eureka: true
        fetch-registry: true
        webclient:
            enabled: true
        service-url:
            defaultZone: ${eureka.props.defaultZone}
    instance:
        hostname: ${eureka.props.hostname}

platform:
    logging:
        level: INFO
        request:
            enabled: true
            include-query-string: true
            include-client-ip: false
            # excluded-paths:
            #     - /api/**
        exception-logging:
            enabled: true
        file:
            directory: logs
            name: application
            max-size: 50MB
            max-history: 30
            total-size-cap: 512MB
        # pattern:
        # console: "%d %-5level[%X{correlationId}] [%thread] %logger{36} - %msg%n"
        # file: ${platform.logging.pattern.console}
    rest-client:
        propagation:
            context:
                enabled: true
            bearer-token:
                enabled: true
    security:
        public-paths:
            - "/identity/api/v1/auth/**"
            - "/swagger-ui/**"
            - "/v3/api-docs/**"
        admin-paths:
            - "/actuator/**"
        cors:
            enabled: false
        jwt:
            enabled: true
            issuer: qoap
            authorities-claim: roles
            authority-prefix: ROLE_
            # username-claim: username
            # email-claim: email
            secret: a-string-secret-at-least-256-bits-long
            access-token-expiration: 2h
            refresh-token-expiration: 7d
            clock-skew: 60s
    web:
        enabled: true
